- name: Transfer reset script
  hosts: testHost
#  remote_user: test_user
  become: yes
  tasks:
    - name: Transfer the script
      copy:
        src: reset.sh
        dest: /home/test_user
        mode: 0777
- name: Execute the script
  hosts: server
  remote_user: test_user
  sudo: yes
  tasks:
    - name: Execute the script
      shell: sh /home/test_user/test.sh
