---
- hosts: testHost
  vars_files:
    - secrets.yml
  tasks:
    - name: Ensure docker is installed
      apt:
        name: docker.io
        state: present
      become: yes

    - name: Check if Docker container is running
      docker_container_info:
        name: samba_container
      register: container_info

    - name: Copy file
      copy:
        src: Dockerfile
        dest: /home/ansible/tmp
      when: not container_info.exists

    - name: Copy file
      copy:
        src: smb.conf
        dest: /home/ansible/tmp
      when: not container_info.exists

    - name: Copy start script
      copy:
        src: start.sh
        dest: /home/ansible/tmp
        mode: 0777

    - name: Copy user setup script
      copy:
        src: user_setup.sh
        dest: /home/ansible/tmp
        mode: 0777

    - name: Build Docker image
      docker_image:
        name: samba_img
        build:
          path: /home/ansible/tmp
      when: not container_info.exists
     
#    - name: Check if Dockerfile exists
#      stat:
#        path: /home/ansible/tmp/Dockerfile
#      register: dockerfile_stat

    - name: Delete Dockerfile
      file:
        path: /home/ansible/tmp/Dockerfile
        state: absent
#      when: not dockerfile_stat.exists
 
    - name: Run Docker container
      docker_container:
        name: samba_container
        image: samba_img
        state: started
        recreate: yes
        volumes:
          - "/home/udavid:/mnt"
        env:
          SAMBA_USER: "{{ samba_user }}"
          SAMBA_PASSWORD: "{{ samba_password }}"
        network_mode: host
      when: not container_info.exists

    - name: Start Docker container
      docker_container:
        name: samba_container
        image: samba_img
        state: started
...
